main: org.modularsoft.PlayerHeadHunt.PlayerHeadHuntMain
name: PlayerHeadHunt
description: An Player Head Hunt minigame.
version: 1.2.0
author: ModularSoft
api-version: 1.19
depend: [WorldEdit]

commands:
  heads:
    description: Grab the amount of heads you have.
    usage: /heads
    aliases: [eggs, presents]
  leaderboard:
    description: Show the 5 best heads hunters on the Server.
    usage: /leaderboard
    aliases: [lb]
  debugheadhunt:
    description: Debug command for developers.
    usage: /debugheadhunt <clearheads|countheads>
    aliases: [ dhh ]